import React, { useState, useEffect, useMemo } from 'react';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

// --- Configuración de Supabase ---
// ¡IMPORTANTE! Reemplaza esto con tu URL y tu Clave Anónima (anon key)
const supabaseUrl = 'https://cnfkofvfnpoespbpcwak.supabase.co'; // Ejemplo: 'https://xxxxxxxx.supabase.co'
const supabaseKey = 'sb_publishable_-G0zczgQQIVMu2dXNvcV4g_6-WX7Bw9'; // Tu 'anon' key pública
// --- --- --- --- --- --- --- --- --- ---

const supabase: SupabaseClient = createClient(supabaseUrl, supabaseKey);

// --- SQL (para referencia) ---
/*
  CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Confirmada', 'Cancelada'
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
  CREATE POLICY "Public can create appointments" ON appointments FOR INSERT WITH CHECK (true);
  CREATE POLICY "Public can read all appointments" ON appointments FOR SELECT USING (true);
  CREATE POLICY "Public can update appointments" ON appointments FOR UPDATE USING (true);
*/

// --- Constantes de Horarios ---
const ALL_TIME_SLOTS = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '12:00', '12:30', '13:00', '13:30', '14:00', '14:30',
  '15:00', '15:30', '16:00', '16:30' // 9:00 a 17:00
];
const MAX_SLOTS_PER_DAY = ALL_TIME_SLOTS.length;

// --- Tipos de Datos ---
interface Appointment {
  id: number;
  name: string;
  date: string;
  time: string;
  type: string;
  status: 'Pendiente' | 'Confirmada' | 'Cancelada';
  created_at: string;
}

// --- Componente de Calendario Reutilizable ---
// Lo convertimos en un componente para poder usarlo tanto en la vista de cliente como en la de admin-reagendar
const Calendar: React.FC<{
  selectedDate: string;
  onDateSelect: (dateStr: string) => void;
  month: Date;
  onMonthChange: (amount: number) => void;
  dailyCounts: Map<string, number>;
  todayStr: string;
}> = ({ selectedDate, onDateSelect, month, onMonthChange, dailyCounts, todayStr }) => {
  
  const year = month.getFullYear();
  const monthIdx = month.getMonth();
  const firstDay = new Date(year, monthIdx, 1).getDay(); // 0 (Sun) - 6 (Sat)
  const daysInMonth = new Date(year, monthIdx + 1, 0).getDate();
  const startOffset = (firstDay === 0) ? 6 : firstDay - 1; // Lunes como 0

  const days = [];
  for (let i = 0; i < startOffset; i++) {
    days.push(<div key={`blank-${i}`} className="p-2"></div>);
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const dateStr = formatDate(new Date(year, monthIdx, day));
    const count = dailyCounts.get(dateStr) || 0;
    const isFull = count >= MAX_SLOTS_PER_DAY;
    const isPast = dateStr < todayStr;
    const isSelected = dateStr === selectedDate;

    let dayClass = 'cursor-pointer transition-colors duration-200';
    if (isPast) {
      dayClass = 'text-gray-400 bg-gray-50 cursor-not-allowed';
    } else if (isSelected) {
      // Estilo Primario (Azul Marino)
      dayClass += ' bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] font-bold';
    } else if (isFull) {
      // Naranja (Lleno) - Usando 'muted' como base
      dayClass += ' bg-orange-100 text-orange-600 hover:bg-orange-200';
    } else {
      // Verde (Disponible) - CAMBIADO A VERDE CLARO
      dayClass += ' bg-green-100 text-green-800 hover:bg-green-200';
    }

    days.push(
      <div
        key={`day-${day}`}
        className={`flex items-center justify-center h-10 w-10 rounded-full text-sm ${dayClass}`}
        onClick={() => {
          if (!isPast) {
            const newDate = new Date(year, monthIdx, day);
            onDateSelect(formatDate(newDate));
          }
        }}
      >
        {day}
      </div>
    );
  }

  return (
    <div className="md:col-span-2">
      <div className="flex justify-between items-center mb-4">
        <button type="button" onClick={() => onMonthChange(-1)} className="px-4 py-2 bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))] rounded-lg hover:bg-[hsl(var(--accent))] transition-colors">&lt;</button>
        <h3 className="text-xl font-semibold text-center">
          {month.toLocaleString('es-ES', { month: 'long', year: 'numeric' })}
        </h3>
        <button type="button" onClick={() => onMonthChange(1)} className="px-4 py-2 bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))] rounded-lg hover:bg-[hsl(var(--accent))] transition-colors">&gt;</button>
      </div>
      <div className="grid grid-cols-7 gap-2 text-center font-medium text-gray-600 mb-2">
        <div>L</div><div>M</div><div>M</div><div>J</div><div>V</div><div>S</div><div>D</div>
      </div>
      <div className="grid grid-cols-7 gap-2 text-center">
        {days}
      </div>
    </div>
  );
};

// --- Componente de Horarios Reutilizable ---
const TimeSlots: React.FC<{
  selectedDate: string;
  selectedTime: string;
  onTimeSelect: (slot: string) => void;
  appointments: Appointment[];
  todayStr: string;
}> = ({ selectedDate, selectedTime, onTimeSelect, appointments, todayStr }) => {
  if (!selectedDate) return null;

  const takenSlots = new Set(
    appointments
      .filter(app => app.date === selectedDate && app.status !== 'Cancelada')
      .map(app => app.time.substring(0, 5)) // 'HH:MM:SS' -> 'HH:MM'
  );

  const isPast = selectedDate < todayStr;
  if (isPast) return null;

  return (
    <div className="md:col-span-2">
      <h4 className="mb-4 font-semibold text-gray-700 text-lg">Selecciona una Hora para el {selectedDate}</h4>
      <div className="grid grid-cols-3 sm:grid-cols-4 gap-3">
        {ALL_TIME_SLOTS.map(slot => {
          const isTaken = takenSlots.has(slot);
          const isSelected = selectedTime === slot;

          return (
            <button
              type="button"
              key={slot}
              disabled={isTaken}
              onClick={() => onTimeSelect(slot)}
              className={`w-full p-3 rounded-lg font-medium transition-all duration-200
                ${isTaken ? 'bg-gray-200 text-gray-400 cursor-not-allowed line-through' : ''}
                ${!isTaken && isSelected ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] ring-2 ring-[hsl(var(--ring))]' : ''}
                ${!isTaken && !isSelected ? 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--accent))]' : ''}
              `}
            >
              {slot}
            </button>
          );
        })}
      </div>
    </div>
  );
};

// --- Función de Utilidad ---
const formatDate = (d: Date): string => d.toISOString().split('T')[0];

// --- Componente Principal ---
const AppointmentsSupabase: React.FC = () => {
  // --- Estado de la UI ---
  const [view, setView] = useState<'client' | 'admin'>('client');
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // --- Estado del Formulario (Cliente) ---
  const [name, setName] = useState('');
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');
  const [type, setType] = useState('Primera Vez');
  const [clientMonth, setClientMonth] = useState(new Date());

  // --- Estado de Reagendado (Admin) ---
  const [reschedulingAppt, setReschedulingAppt] = useState<Appointment | null>(null);
  const [newDate, setNewDate] = useState('');
  const [newTime, setNewTime] = useState('');
  const [adminMonth, setAdminMonth] = useState(new Date());

  // --- Estado de Datos (Compartido) ---
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [dailyCounts, setDailyCounts] = useState<Map<string, number>>(new Map());
  const todayStr = useMemo(() => formatDate(new Date()), []);

  // Función para cargar citas y procesar conteos
  const fetchAppointments = async () => {
    if (!supabase) return;
    setLoading(true);
    
    const { data, error } = await supabase
      .from('appointments')
      .select('*')
      .order('date', { ascending: true })
      .order('time', { ascending: true });

    if (error) {
      console.error("Error fetching appointments:", error);
      setMessage({ type: 'error', text: 'No se pudieron cargar las citas.' });
    } else if (data) {
      setAppointments(data as Appointment[]);
      
      const counts = new Map<string, number>();
      for (const app of data) {
        if (app.status !== 'Cancelada') {
          counts.set(app.date, (counts.get(app.date) || 0) + 1);
        }
      }
      setDailyCounts(counts);
    }
    setLoading(false);
  };

  // Efecto 1: Carga inicial y suscripción en tiempo real
  useEffect(() => {
    fetchAppointments(); // Carga inicial
    const channel = supabase
      .channel('public:appointments')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'appointments' },
        (payload) => {
          console.log('Change received!', payload);
          fetchAppointments(); // Recargar todo al recibir un cambio
        }
      )
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, []);

  // --- Manejadores de Eventos (Cliente) ---
  const handleSubmitBooking = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !date || !time || !type) {
      setMessage({ type: 'error', text: 'Por favor, completa nombre, tipo, y selecciona un día y hora.' });
      return;
    }
    setLoading(true);
    const { error } = await supabase
      .from('appointments')
      .insert([{ name, date, time, type, status: 'Pendiente' }]);

    if (error) {
      console.error("Error adding document: ", error);
      setMessage({ type: 'error', text: 'Hubo un error al agendar tu cita. Intenta de nuevo.' });
    } else {
      setMessage({ type: 'success', text: '¡Cita agendada con éxito!' });
      setName(''); setDate(''); setTime(''); setType('Primera Vez');
    }
    setLoading(false);
  };

  // --- Manejadores de Eventos (Admin) ---
  const handleUpdateStatus = async (
    id: number,
    newStatus: 'Confirmada' | 'Cancelada'
  ) => {
    if (!supabase) return;
    const { error } = await supabase
      .from('appointments')
      .update({ status: newStatus })
      .eq('id', id);
    if (error) {
      console.error("Error updating status: ", error);
      setMessage({ type: 'error', text: 'No se pudo actualizar el estado.' });
    }
  };

  // Inicia el modo de reagendar
  const startReschedule = (app: Appointment) => {
    setReschedulingAppt(app);
    setNewDate(app.date); // Empezar con la fecha actual de la cita
    setNewTime(app.time); // Empezar con la hora actual
    setAdminMonth(new Date(app.date + 'T00:00:00')); // Centrar calendario en esa fecha
    setView('admin'); // Asegurarse de que estamos en la vista admin
  };

  // Guarda la cita reagendada
  const handleRescheduleSubmit = async () => {
    if (!reschedulingAppt || !newDate || !newTime) {
      setMessage({ type: 'error', text: 'Por favor, selecciona una nueva fecha y hora.' });
      return;
    }
    setLoading(true);
    const { error } = await supabase
      .from('appointments')
      .update({
        date: newDate,
        time: newTime,
        status: 'Pendiente' // Al reagendar, se marca como pendiente de confirmación
      })
      .eq('id', reschedulingAppt.id);

    if (error) {
      setMessage({ type: 'error', text: 'No se pudo reagendar la cita.' });
    } else {
      setMessage({ type: 'success', text: '¡Cita reagendada con éxito!' });
      setReschedulingAppt(null); // Salir del modo reagendar
      setNewDate('');
      setNewTime('');
    }
    setLoading(false);
  };

  // --- Renderizado del Componente ---

  // Botón genérico con estilos del tema
  const AppButton: React.FC<React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'destructive' | 'secondary' }> = ({ children, variant = 'primary', className = '', ...props }) => {
    let colors = '';
    switch (variant) {
      case 'primary':
        colors = 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] hover:bg-[hsl(var(--primary)/0.9)]'; break;
      case 'destructive':
        colors = 'bg-[hsl(var(--destructive))] text-[hsl(var(--destructive-foreground))] hover:bg-[hsl(var(--destructive)/0.9)]'; break;
      case 'secondary':
        colors = 'bg-[hsl(var(--secondary))] text-[hsl(var(--secondary-foreground))] hover:bg-[hsl(var(--secondary)/0.8)]'; break;
    }
    return (
      <button
        className={`px-4 py-2 rounded-lg font-semibold transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-[hsl(var(--ring))] focus:ring-offset-2 ${colors} ${className}`}
        {...props}
      >
        {children}
      </button>
    );
  };

  return (
    <div className="max-w-4xl mx-auto p-4 md:p-8 bg-background shadow-soft rounded-[var(--radius)] mt-10 text-foreground">
      
      {/* --- Pestañas para cambiar de vista --- */}
      {!reschedulingAppt && ( // Ocultar pestañas si estamos reagendando
        <div className="flex flex-col sm:flex-row justify-center gap-2 mb-8 bg-[hsl(var(--muted))] p-2 rounded-xl">
          <button
            onClick={() => setView('client')}
            className={`w-full px-6 py-3 rounded-lg font-semibold transition-all duration-300 ${
              view === 'client'
                ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] shadow-medium'
                : 'bg-transparent text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--accent))]'
            }`}
          >
            Agendar Cita
          </button>
          <button
            onClick={() => setView('admin')}
            className={`w-full px-6 py-3 rounded-lg font-semibold transition-all duration-300 ${
              view === 'admin'
                ? 'bg-gray-800 text-white shadow-lg' // Mantener admin oscuro o cambiar a primary?
                : 'bg-transparent text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--accent))]'
            }`}
          >
            Ver Citas (Admin)
          </button>
        </div>
      )}

      {/* --- Mensajes de estado --- */}
      {message && (
        <div
          className={`p-4 rounded-lg mb-6 text-center font-medium ${
            message.type === 'success'
              ? 'bg-green-100 text-green-800'
              : 'bg-red-100 text-red-800'
          }`}
        >
          {message.text}
        </div>
      )}

      {/* --- VISTA CLIENTE: Formulario de Citas --- */}
      {view === 'client' && !reschedulingAppt && (
        <div>
          <h2 className="text-3xl font-bold text-center mb-6 text-[hsl(var(--primary))]">
            Agenda tu Cita
          </h2>
          <form onSubmit={handleSubmitBooking} className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Campo Nombre */}
            <div className="flex flex-col">
              <label htmlFor="name" className="mb-2 font-semibold text-[hsl(var(--foreground))]">
                Nombre Completo
              </label>
              <input
                type="text"
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Ej. Juan Pérez"
                className="w-full p-3 border border-[hsl(var(--border))] rounded-lg bg-[hsl(var(--background))] focus:ring-2 focus:ring-[hsl(var(--ring))] focus:outline-none"
              />
            </div>

            {/* Campo Tipo de Cita */}
            <div className="flex flex-col">
              <label htmlFor="type" className="mb-2 font-semibold text-[hsl(var(--foreground))]">
                Tipo de Cita
              </label>
              <select
                id="type"
                value={type}
                onChange={(e) => setType(e.target.value)}
                className="w-full p-3 border border-[hsl(var(--border))] rounded-lg bg-[hsl(var(--background))] focus:ring-2 focus:ring-[hsl(var(--ring))] focus:outline-none"
              >
                <option>Primera Vez</option>
                <option>Seguimiento</option>
                <option>Limpieza</option>
                <option>Ortodoncia</option>
                <option>Otro</option>
              </select>
            </div>

            {/* --- CALENDARIO CLIENTE --- */}
            <Calendar
              selectedDate={date}
              onDateSelect={(dateStr) => { setDate(dateStr); setTime(''); }}
              month={clientMonth}
              onMonthChange={(amount) => setClientMonth(prev => new Date(prev.getFullYear(), prev.getMonth() + amount, 1))}
              dailyCounts={dailyCounts}
              todayStr={todayStr}
            />
            
            {/* --- HORARIOS CLIENTE --- */}
            <TimeSlots
              selectedDate={date}
              selectedTime={time}
              onTimeSelect={setTime}
              appointments={appointments}
              todayStr={todayStr}
            />

            {/* Botón de Enviar */}
            <div className="md:col-span-2">
              <AppButton
                type="submit"
                disabled={loading}
                className="w-full py-3 px-6 mt-4 text-lg"
              >
                {loading ? 'Agendando...' : 'Agendar Cita'}
              </AppButton>
            </div>
          </form>
        </div>
      )}

      {/* --- VISTA ADMIN: Lista de Citas --- */}
      {view === 'admin' && !reschedulingAppt && (
        <div>
          <h2 className="text-3xl font-bold text-center mb-6 text-gray-800">
            Panel de Administrador de Citas
          </h2>
          {loading && <div className="text-center text-gray-600">Cargando citas...</div>}
          
          {!loading && appointments.length === 0 && (
            <div className="text-center text-gray-500 p-6 bg-[hsl(var(--muted))] rounded-lg">
              No hay citas pendientes.
            </div>
          )}

          {!loading && appointments.length > 0 && (
            <div className="space-y-4">
              {appointments.map((app) => (
                <div
                  key={app.id}
                  className="p-5 bg-[hsl(var(--card))] border border-[hsl(var(--border))] rounded-xl shadow-soft flex flex-wrap items-center justify-between gap-4"
                >
                  <div className="flex-1 min-w-[200px]">
                    <p className="font-bold text-lg text-[hsl(var(--card-foreground))]">{app.name}</p>
                    <p className="text-[hsl(var(--muted-foreground))]">Tipo: {app.type}</p>
                    <p className="text-[hsl(var(--muted-foreground))]">
                      Fecha: <span className="font-medium text-[hsl(var(--card-foreground))]">{app.date}</span> a las <span className="font-medium text-[hsl(var(--card-foreground))]">{app.time}</span>
                    </p>
                  </div>
                  <div className="flex-shrink-0">
                    <span
                      className={`px-3 py-1 rounded-full font-semibold text-sm ${
                        app.status === 'Pendiente'
                          ? 'bg-yellow-100 text-yellow-800'
                          : app.status === 'Confirmada'
                          ? 'bg-green-100 text-green-800'
                          : 'bg-red-100 text-red-800'
                      }`}
                    >
                      {app.status}
                    </span>
                  </div>
                  <div className="flex flex-col sm:flex-row gap-2">
                    {app.status === 'Pendiente' && (
                      <>
                        <AppButton variant="primary" onClick={() => handleUpdateStatus(app.id, 'Confirmada')} className="text-sm">Confirmar</AppButton>
                        <AppButton variant="destructive" onClick={() => handleUpdateStatus(app.id, 'Cancelada')} className="text-sm">Cancelar</AppButton>
                      </>
                    )}
                    {app.status === 'Confirmada' && (
                      <AppButton variant="destructive" onClick={() => handleUpdateStatus(app.id, 'Cancelada')} className="text-sm">Cancelar</AppButton>
                    )}
                    {/* El botón de Reagendar se muestra siempre */}
                    <AppButton variant="secondary" onClick={() => startReschedule(app)} className="text-sm">Reagendar</AppButton>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* --- VISTA ADMIN: Reagendando Cita Específica --- */}
      {view === 'admin' && reschedulingAppt && (
        <div>
          <h2 className="text-3xl font-bold text-center mb-2 text-gray-800">Reagendar Cita</h2>
          <p className="text-center text-lg text-[hsl(var(--muted-foreground))] mb-6">
            Para: <span className="font-semibold text-[hsl(var(--primary))]">{reschedulingAppt.name}</span>
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 border border-[hsl(var(--border))] rounded-xl bg-[hsl(var(--background))]">
            {/* --- CALENDARIO ADMIN --- */}
            <Calendar
              selectedDate={newDate}
              onDateSelect={(dateStr) => { setNewDate(dateStr); setNewTime(''); }}
              month={adminMonth}
              onMonthChange={(amount) => setAdminMonth(prev => new Date(prev.getFullYear(), prev.getMonth() + amount, 1))}
              dailyCounts={dailyCounts}
              todayStr={todayStr}
            />
            
            {/* --- HORARIOS ADMIN --- */}
            <TimeSlots
              selectedDate={newDate}
              selectedTime={newTime}
              onTimeSelect={setNewTime}
              appointments={appointments.filter(a => a.id !== reschedulingAppt.id)} // Excluir la cita actual de los slots ocupados
              todayStr={todayStr}
            />

            {/* Botones de Acción */}
            <div className="md:col-span-2 flex flex-col sm:flex-row gap-4 mt-4">
              <AppButton
                onClick={handleRescheduleSubmit}
                disabled={loading || !newDate || !newTime}
                className="w-full py-3"
              >
                {loading ? 'Guardando...' : 'Confirmar Reagendado'}
              </AppButton>
              <AppButton
                variant="secondary"
                onClick={() => setReschedulingAppt(null)} // Cancelar reagendado
                className="w-full py-3"
              >
                Cancelar
              </AppButton>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default AppointmentsSupabase;